---

- name: Install required packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - curl
      - jq

- name: Wait for port 9000 to become open on the host, don't start checking for 10 seconds
  wait_for:
    port: 9000
    delay: 10


- name: Wait for node to application to come up and sync
  script: wait-for-sync.sh
  args:
    become: yes
    chdir: /home/{{ ansible_user }}/
